### ISSUE TITLE
Python style guide

### ISSUE THREAD

**Issue by lunardog** [cookpad/styleguide#39]
We use Python for machine learning and data mining a lot. I'd like to compile a style guide for Python. Some questions to python users:

1. do you depend on python 2 or can we make python 3 default?
1. do you use `pep8` or similar linter?
1. what testing framework do you use? 
1. do you put your code in jupyter notebooks or `.py` files, or both?

**Comment by lunardog** [comment]
Python style guide at Google: https://google.github.io/styleguide/pyguide.html

**Comment by l15n** [comment]
How about we start with pep8 and ... prefer python 3?

Other people I know who write python regularly include @giginet and @ayemos ... and @yoshiori too

**Comment by OisinB** [comment]
1. Python 2 support please!
2. `pep8` 👍 
3. I personally use unittest, but am happy to use whatever
4. Both - notebooks for data exploring, `.py` files for actual models.
5. The Google style guide is a good standard, imho

**Comment by uiureo** [comment]
1. I prefer python 3 for better unicode support
2. `flake8`
3. using `pytest`, but whatever
4. both

**Comment by giginet** [comment]
1. We should use Python 3 as possible. because we live in 2017.
2. I'm using pep8
3. `unittest` on the standard modules. In Python 3, it is powerful and easy to use.
4. `.py`files

**Comment by kenneyd** [comment]
1. Python3 preferred
2. Using pycodestyle (pep8)
3. unittest is good
4. py files only right now

**Comment by lunardog** [comment]
The issue seems to be stale. If you have any comments about python style, please open a new one.
