### ISSUE TITLE
Ruby: Revise a rule related to optional arguments and keyword arguments

### ISSUE THREAD

**Issue by nekketsuuu** [cookpad/styleguide#60]
[Rubocop 0.80.0](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md#0800-2020-02-18) (released 2020-02-18) removed `Style/BracesAroundHashParameters` cop. rubocop-hq/rubocop#7641 says the removal was because the curly braces may have the meaning since Ruby 2.7.

https://github.com/cookpad/styleguide/blob/590bca6dafc9f879518fc0190f0d023387066e31/.rubocop.yml#L264-L266

I think it's a good time to reconsider the above rule.

My opinion is:

* Remove `Style/BracesAroundHashParameters` from `.rubocop.yml`.
* Rewrite the rule in English and Japanese to mention keyword arguments and hash. Ref: rubocop-hq/ruby-style-guide#788

Any thoughts?

**Comment by nekketsuuu** [comment]
How about...

> [SHOULD] Distinguish between using a hash and using keyword arguments in method calls.
> 
> ```ruby
> def foo(a:, b:)
>   p(a, b)
> end
> 
> def bar(hash)
>   p(hash)
> end
> 
> # good
> foo(a: 1, b: 2)
> # good
> bar({a: 1, b: 2})
> 
> # bad - foo expects keyword arguments, but it passes a hash
> foo({a: 1, b: 2})
> # bad - bar expects a hash, but it passes keyword arguments
> bar(a: 1, b: 2)
> ```

The example above is a slightly modified version of https://github.com/rubocop-hq/ruby-style-guide/issues/788.

**Comment by mame** [comment]
Vote for the removal.  The documents also looks great to me.
